import { LegalLayout } from '../../components/LegalLayout/LegalLayout';

export function Disclaimer() {
  return (
    <LegalLayout title="Disclaimer" lastUpdated="August 28, 2026">
      <section id="general">
        <h2>General Disclaimer</h2>
        <p>
          The information provided by StudyMapper is for general educational and informational purposes only. 
          All information on the application is provided in good faith, however we make no representation or 
          warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, 
          availability, or completeness of any information.
        </p>
      </section>

      <section id="ai-content">
        <h2>AI-Generated Content Accuracy</h2>
        <p>
          StudyMapper utilizes artificial intelligence (AI) models to generate study notes, answers, 
          coding problems, and other educational content. While we strive for accuracy, AI-generated content:
        </p>
        <ul>
          <li>May contain errors, inaccuracies, or outdated information</li>
          <li>Should not be considered a substitute for official textbooks, lectures, or instructor guidance</li>
          <li>Must be verified against authoritative academic sources before use in examinations or assignments</li>
          <li>May not reflect the specific curriculum requirements of your institution</li>
        </ul>
      </section>

      <section id="educational-purpose">
        <h2>Educational Purpose Only</h2>
        <p>
          StudyMapper is designed as a supplementary study aid and is not intended to replace formal education, 
          professional tutoring, or academic advising. The use of this application does not guarantee academic success, 
          passing grades, or qualification for any degree or certification.
        </p>
      </section>

      <section id="exam-predictions">
        <h2>Exam Score Predictions</h2>
        <p>
          Any exam score predictions, performance estimates, or mock test analyses generated by StudyMapper 
          are purely estimates based on limited data. These predictions:
        </p>
        <ul>
          <li>Are not guarantees of actual exam performance</li>
          <li>Do not account for exam-day variables such as stress, health, or question difficulty</li>
          <li>Should be used as motivational tools rather than definitive forecasts</li>
        </ul>
      </section>

      <section id="academic-integrity">
        <h2>Academic Integrity</h2>
        <p>
          Users are solely responsible for ensuring that their use of StudyMapper complies with their institution's 
          academic integrity policies. StudyMapper should not be used to:
        </p>
        <ul>
          <li>Cheat on examinations or assignments</li>
          <li>Plagiarize content without proper attribution</li>
          <li>Violate any academic honor codes or policies</li>
        </ul>
      </section>

      <section id="placement">
        <h2>Placement & Career Outcomes</h2>
        <p>
          StudyMapper provides placement preparation materials, mock interviews, and career guidance. However, 
          we make no guarantees regarding job placement, interview success, salary outcomes, or career advancement. 
          Results depend on individual effort, market conditions, and numerous factors beyond our control.
        </p>
      </section>

      <section id="external-links">
        <h2>External Links</h2>
        <p>
          StudyMapper may contain links to external websites. We do not endorse, guarantee, or assume responsibility 
          for the accuracy or reliability of any information offered by third-party websites linked through our application.
        </p>
      </section>
    </LegalLayout>
  );
}
