import { LegalLayout } from '../../components/LegalLayout/LegalLayout';

export function TermsAndConditions() {
  return (
    <LegalLayout title="Terms & Conditions" lastUpdated="August 28, 2026">
      <section id="acceptance">
        <h2>Acceptance of Terms</h2>
        <p>
          By accessing or using StudyMapper, you agree to be bound by these Terms & Conditions. 
          If you disagree with any part of the terms, you may not access the service.
        </p>
      </section>

      <section id="description">
        <h2>Description of Service</h2>
        <p>
          StudyMapper is an offline-first, AI-powered learning workspace designed for engineering and college students. 
          The application transforms static syllabuses and notes into interactive, adaptive learning experiences 
          using client-side AI processing and local data storage.
        </p>
      </section>

      <section id="accounts">
        <h2>User Accounts & Responsibilities</h2>
        <ul>
          <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
          <li>You must provide accurate and complete information during registration.</li>
          <li>You are responsible for all activities that occur under your account.</li>
          <li>You must notify us immediately of any unauthorized use of your account.</li>
        </ul>
      </section>

      <section id="acceptable-use">
        <h2>Acceptable Use</h2>
        <p>You agree NOT to:</p>
        <ul>
          <li>Reverse engineer, decompile, or disassemble any part of the application</li>
          <li>Share, sell, or redistribute your OpenRouter API key or AI credits</li>
          <li>Use the service for any illegal purpose or to violate any laws</li>
          <li>Upload malicious code, viruses, or harmful content</li>
          <li>Attempt to gain unauthorized access to any part of the service</li>
          <li>Use automated scripts or bots to access the service</li>
        </ul>
      </section>

      <section id="intellectual-property">
        <h2>Intellectual Property</h2>
        <p>
          <strong>Your Content:</strong> You retain all rights to the study materials, notes, and content you create. 
          StudyMapper claims no ownership over your educational content.
        </p>
        <p>
          <strong>AI-Generated Content:</strong> Content generated by AI models through StudyMapper is provided 
          for educational purposes. You may use this content for personal study purposes. We recommend verifying 
          AI-generated information against official academic sources.
        </p>
        <p>
          <strong>StudyMapper IP:</strong> All rights, title, and interest in and to the StudyMapper application, 
          including all software, designs, logos, and trademarks, are and will remain the exclusive property of 
          StudyMapper and its licensors.
        </p>
      </section>

      <section id="termination">
        <h2>Termination</h2>
        <p>
          We may terminate or suspend your account immediately, without prior notice or liability, for any reason, 
          including breach of these Terms. Upon termination, your right to use the service will immediately cease. 
          Your locally stored data remains on your device.
        </p>
      </section>

      <section id="liability">
        <h2>Limitation of Liability</h2>
        <p>
          StudyMapper and its creators shall not be liable for any indirect, incidental, special, consequential, 
          or punitive damages resulting from your use of or inability to use the service. This includes but is not 
          limited to academic performance, exam results, or placement outcomes.
        </p>
        <p>
          AI-generated content is provided &quot;as is&quot; without warranties of accuracy, completeness, or reliability. 
          Always verify critical information with official academic sources.
        </p>
      </section>

      <section id="governing-law">
        <h2>Governing Law</h2>
        <p>
          These Terms shall be governed by and construed in accordance with the laws of the jurisdiction 
          in which StudyMapper operates, without regard to its conflict of law provisions.
        </p>
      </section>

      <section id="changes">
        <h2>Changes to Terms</h2>
        <p>
          We reserve the right to modify these terms at any time. We will provide notice of significant changes 
          by updating the &quot;Last Updated&quot; date. Your continued use of the service after such changes constitutes 
          acceptance of the new terms.
        </p>
      </section>
    </LegalLayout>
  );
}
